### ISSUE TITLE
Accidental?

### ISSUE THREAD

**Issue by ggravlingen** [ffleurey/ThingML-Tradfri#1]
Hi,

Just browsed around and saw your key here. Don’t know if it’s accidental?

https://github.com/ffleurey/ThingML-Tradfri/blob/master/tradfri-java/src/main/java/org/thingml/tradfri/Main.java

**Comment by ffleurey** [comment]
Thanks for the message. I left it there (and a couple other places) as example. It should not be a big deal since it is only available on the LAN and the keys I left are for a couple of test IKEA bridges I am using, nothing really in use. Cheers!

**Comment by ggravlingen** [comment]
Alrighty!
